#バージョンによって書き方が異なる
version: '3.9'

#サービスとはアプリケーションを動かすための要素
services:
  web:
    #コンテナを起動するDocker Image
    image: nginx:1.23.0
    container_name: web
    depends_on:
      - frontend
      - backend
    links:
      - frontend
      - backend
    volumes:
      - "./web/nginx.conf:/etc/nginx/conf.d/default.conf"
    #ポートの開放左にホストのポート右にコンテナのポート
    ports:
      - 80:80
  frontend:
    image: node:18.9.1
    container_name: frontend
    volumes:
      - "./frontend/bonne-coordination:/projects/frontend/bonne-coordination"
    ports:
      - 3000:3000
    working_dir: /projects/frontend/bonne-coordination
    tty: true
    command: bash -c "npm i && npm start"
  backend:
    image: golang:1.19.1
    container_name: backend
    working_dir: /app
    #Service同士の依存関係
    depends_on:
      - db
    links:
      - db
    volumes:
      - './backend:/app'
    ports:
      - 8080:8080
    tty: true
  db:
    image: postgres:14.4
    container_name: db
    #実行時に再起動するか
    restart: always
    #DBについての環境変数設定
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS="--encoding=UTF8"
    #マウントする設定ファイルのパスを指定
    volumes: 
      - './db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql'
    #DBの
    ports:
      - 5432:5432
    tty: true

  

